//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancosangreEntities : DbContext
    {
        public bancosangreEntities()
            : base("name=bancosangreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstadoDonacion> EstadoDonacion { get; set; }
        public virtual DbSet<Cuestionario> Cuestionario { get; set; }
        public virtual DbSet<DatoDemograficoCuestionario> DatoDemograficoCuestionario { get; set; }
        public virtual DbSet<DestinoDonacion> DestinoDonacion { get; set; }
        public virtual DbSet<Donacion> Donacion { get; set; }
        public virtual DbSet<Donante> Donante { get; set; }
        public virtual DbSet<GrupoFactor> GrupoFactor { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<PreguntaCuestionario> PreguntaCuestionario { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<EstadoDonante> EstadoDonante { get; set; }
        public virtual DbSet<ExamenesSerologicos> ExamenesSerologicos { get; set; }
        public virtual DbSet<DonacionExamenSerologico> DonacionExamenSerologico { get; set; }
    }
}
