//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoDemograficoCuestionario
    {
        public System.Guid IdDatoDemograficoCuestionario { get; set; }
        public System.Guid IdCuestionario { get; set; }
        public string Etiqueta { get; set; }
        public string Dato { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual Cuestionario Cuestionario { get; set; }
    }
}
