//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoDemograficoCuestionario
    {
        public System.Guid IdDatoDemograficoCuestionario { get; set; }
        public System.Guid IdCuestionario { get; set; }
        public string Etiqueta { get; set; }
        public string Dato { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual Cuestionario Cuestionario { get; set; }
    }
}
