//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public string NroRegistro { get; set; }
        public int IdDonante { get; set; }
        public int IdDestino { get; set; }
        public string Material { get; set; }
        public string Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Peso { get; set; }
        public Nullable<int> IdEstadoDonacion { get; set; }
    
        public virtual DestinoDonacion DestinoDonacion { get; set; }
        public virtual Donante Donante { get; set; }
        public virtual EstadoDonacion EstadoDonacion { get; set; }
    }
}
