//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonacionExamenSerologico
    {
        public string NroRegistro { get; set; }
        public int IdExamenSerologico { get; set; }
        public bool Resultado { get; set; }
    
        public virtual Donacion Donacion { get; set; }
        public virtual ExamenesSerologicos ExamenesSerologicos { get; set; }
    }
}
