//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonacionExamenSerologico
    {
        public string NroRegistro { get; set; }
        public int IdExamenSerologico { get; set; }
        public bool Resultado { get; set; }
    
        public virtual Donacion Donacion { get; set; }
        public virtual ExamenesSerologicos ExamenesSerologicos { get; set; }
    }
}
