//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donacion()
        {
            this.DonacionExamenSerologico = new HashSet<DonacionExamenSerologico>();
        }
    
        public string NroRegistro { get; set; }
        public long IdDonante { get; set; }
        public int IdDestino { get; set; }
        public string Material { get; set; }
        public string Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Peso { get; set; }
        public Nullable<int> IdEstadoDonacion { get; set; }
        public Nullable<System.Guid> IdCuestionario { get; set; }
    
        public virtual DestinoDonacion DestinoDonacion { get; set; }
        public virtual Donante Donante { get; set; }
        public virtual EstadoDonacion EstadoDonacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionExamenSerologico> DonacionExamenSerologico { get; set; }
        public virtual Cuestionario Cuestionario { get; set; }
    }
}
