//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.PreguntaCuestionario = new HashSet<PreguntaCuestionario>();
        }
    
        public int IdPregunta { get; set; }
        public string TextoPregunta { get; set; }
        public bool EsCerrada { get; set; }
        public bool CausalRechazo { get; set; }
        public bool Mostrar { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool EsTitulo { get; set; }
        public bool LineaCompleta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaCuestionario> PreguntaCuestionario { get; set; }
    }
}
