//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoSangre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.PreguntaCuestionario = new HashSet<PreguntaCuestionario>();
        }
    
        public int IdPregunta { get; set; }
        public string TextoPregunta { get; set; }
        public bool EsCerrada { get; set; }
        public bool CausalRechazo { get; set; }
        public bool Mostrar { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool EsTitulo { get; set; }
        public bool LineaCompleta { get; set; }
        public bool NuevaLinea { get; set; }
        public Nullable<bool> LineaHorizontal { get; set; }
        public Nullable<bool> RechazoPorPositivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaCuestionario> PreguntaCuestionario { get; set; }
    }
}
